### ISSUE TITLE
Update Buffer checks if found buffer is not equal to null instead of equal to null.

### ISSUE THREAD

**Issue by JocieOaks** [MPSQUARK/BAVCL#38]
Found an issue here that makes it so that UpdateBuffer is constantly allocating new buffers instead of using the buffer that already exists. https://github.com/MPSQUARK/BAVCL/blob/df9ce1948a6d2e8cb1923458090c7a4ff9c77260/BAVCL/Core/GPU/LRU.cs#L236

**Comment by MPSQUARK** [comment]
Good spot. Thanks for reporting. This is very likely a typo. 

I'll get that fixed asap.

**Comment by MPSQUARK** [comment]
Submitted the fix for this to the master branch, in commit c11f3295.
